### ISSUE TITLE
Please add 'install_requires' statements to your setup.py

### ISSUE THREAD

**Issue by yurivict** [lanl/qmasm#10]
https://packaging.python.org/discussions/install-requires-vs-requirements/

You at least use ```pulp```: https://github.com/lanl/qmasm/blob/master/qmasm/problem.py#L17
You need to declare them in 'install_requires' so that they will be always available, vs. only available by accident.

**Comment by spakin** [comment]
But as you see from [`problem.py`](https://github.com/lanl/qmasm/blob/b02225fdb65dae449064760baef394fe34e77a08/qmasm/problem.py#L16-L20), QMASM can work with or without `pulp`.  I don't want to require an obscure package like [PuLP](https://pythonhosted.org/PuLP/) in a [`setup.py`](https://github.com/lanl/qmasm/blob/513b7e3d2f34fd49c20d4beb38b105e3cdad83b1/setup.py) `install_requires` line because that would force it on all users, few of whom care about the QMASM functionality it provides (minimum-energy estimation).

I'm going to mark this issue closed, but do feel free to re-open it if you find other packages that should be listed by `install_requires`.

**Comment by yurivict** [comment]
There are optional 'install_requires' statements too for the situations like this.

**Comment by spakin** [comment]
But aren't those essentially indicating "required if condition *C* is met" (e.g., a particular OS or a particular Python version)?

**Comment by yurivict** [comment]
No, ```extras_require=``` is the optional dependency statement, and it is unconditional.

Usually, some features get enabled when they are present, or some default implementations in the code a re replaced with external packages, like in you case, I guess.

**Comment by spakin** [comment]
So what are you proposing I add to [`setup.py`](https://github.com/lanl/qmasm/blob/513b7e3d2f34fd49c20d4beb38b105e3cdad83b1/setup.py)?  Can you submit a pull request?

**Comment by yurivict** [comment]
It's ok, no need to do anything.
