### ISSUE TITLE
examples in qbsolv mode

### ISSUE THREAD

**Issue by frederic-bapst** [lanl/qmasm#4]
What is the expected outcome when running the examples (eg examples/1of5.qmasm) in qbsolv mode (classical solver, no DWave)? Could you add a couple of lines in the doc/readme about that (command line + output)? 

I've tried something, but it seems it ends with an error (see below). 

Disclaimer: it's my very first steps, and clumsiness on my side is highly probable (shame on me)... 

BTW, I think it's a great project/tool; thanks a lot for sharing this contribution!

```
    /usr/local/bin/qmasm 1of5.qmasm --format qbsolv --run -v

Computed the following strengths:

    chain: -8.0000
    pin:   -8.0000

Encountered the following solver properties:

    Parameter    Value
    -----------  -----
    solver_name  'phony'

Submitting the problem to qbsolv via qmasm-qbsolv.

# 8 bits,  find Min, SubMatrix= 47, -a o, timeout=2592000.0 sec
# 00010000
# -4.00000 Energy of solution
# 0 Number of Partitioned calls, 1 output sample
#  0.00093 seconds of classic cpu time

Solution #1 (energy = -4.00, tally = 1):

    Name(s)  Spin  Boolean
    -------  ----  -------
Traceback (most recent call last):
  File "/usr/local/bin/qmasm-qbsolv", line 87, in <module>
    spin = bits[num]*2 - 1
IndexError: list index out of range
```

**Comment by spakin** [comment]
It looks like D-Wave changed `qbsolv`'s output format since I last tested `qmasm-qbsolv`.  I just modified the way `qmasm-qbsolv` parses its output, which I believe fixes the problem.  Please re-open the issue if it it's still not working for you.

Thanks for the bug report!

— Scott

P.S.  `qmasm` output should look pretty much the same whether or not `--format=qbsolv` is used, except that `qbsolv` returns only a single solution.  See the [`README.md` file in the `examples` directory](https://github.com/lanl/qmasm/tree/master/examples) to get an idea of what that should look like.
