### ISSUE TITLE
Using qmasm with FakeConnection

### ISSUE THREAD

**Issue by sindhura97** [lanl/qmasm#8]
I see that with a fake connection I can only have the solver named 'phony'. If I set the dwave solver to c4-sw_sample, the code fails.
And using the default 'phony' solver, I end up outputting "Without D-Wave's libraries, QMASM can do little more than output qbsolv, MiniZinc, and flattened QMASM files" without any solutions. Could you please help me understand this?

**Comment by spakin** [comment]
QMASM relies on D-Wave's proprietary SAPI library to minimize the Hamiltonian/QUBO.  Without SAPI, all QMASM can do is output the problem coefficients; it can't do anything useful with them.  However, if you install [qbsolv](https://github.com/dwavesystems/qbsolv), you can use that as the solver.  Specify `--format=qbsolv --run` on the `qmasm` command line to go that route.

What I *really* want to do is rewrite QMASM to use [Ocean](https://ocean.dwavesys.com/) instead of SAPI.  Not only is Ocean open-source software, but it also provides a classical solver.  The full QMASM functionality will therefore be available whether you're running on your desktop or on a D-Wave system. Alas, this is a major code change, and I haven't yet found the time to work on it.

**Comment by spakin** [comment]
Closing this issue.  At long last, I rewrote QMASM to use [D-Wave's open-source Ocean API](https://ocean.dwavesys.com/) in place of their proprietary and now-deprecated SAPI library!  As a result, QMASM can run programs using Ocean's integrated software solvers if you don't have access to a D-Wave system.  (Note that through [D-Wave Leap](https://cloud.dwavesys.com/) you can register for free cloud access to D-Wave hardware in case you want to try that out.)
